version: '3.8'

services:
  app:
    build: .
    container_name: flask_app
    ports:
      - "9090:9090"
    environment:
      - FLASK_ENV=development
      - ADDRESS=0.0.0.0
      - PORT=9090
      - DB_HOST=localhost
      - DB_PORT=3306
      - DB_NAME=workshop2024
      - DB_USER=workshop2024
      - DB_PASSWORD=workshop2024
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: mariadb:latest
    container_name: mariadb_db
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=workshop2024
      - MYSQL_USER=workshop2024
      - MYSQL_PASSWORD=workshop2024
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: